name: ci

on: push

env:
  TEST_TAG: image-test
  PICT_VERSION: 3.7.4

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build test image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Build quarkus native image
        run: |
          ./mvnw package -Pnative -Dquarkus.native.container-build=true
      -
        name: Test image runs pict
        # If the string is not found in the output grep will exit with error status
        run: |
          docker run --rm ${{ env.TEST_TAG }} pict | grep "Pairwise Independent Combinatorial Testing"
      -
        name: Build and push main
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            renfis/pict:latest
            renfis/pict:${{ env.PICT_VERSION }}
