name: ci

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: image-test
  PICT_VERSION: 3.7.4

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build test image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test image runs pict
        # If the string is not found in the output grep will exit with error status
        run: |
          docker run --rm ${{ env.TEST_TAG }} pict | grep "ERROR Pairwise Independent Combinatorial Testing ERROR"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            renfis/pict:latest
            renfis/pict:${{ env.PICT_VERSION }}
